const cartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    DECREASE_QUANTITY_CART_ITEM: 'DECREASE_QUANTITY_CART_ITEM'
}

export default cartActionTypes;